// apps/pbswebsite/pages/index.vue
<template>
  <div>
    <Title>Brücken bauen, Menschen verbinden</Title>
    <div class="container mx-auto px-4 pt-36 md:pt-44">
      <h1 class="font-header text-5xl font-bold text-slate-800 md:text-6xl lg:text-7xl">
        Brücken bauen,<br />
        Menschen verbinden
      </h1>
      <p class="mt-8 text-slate-800">
        Wir sind die Potsdamer Bürgerstiftung und fördern als Mitmach-Stiftung
        ehrenamtliches Engagement.
      </p>
      <p class="pt-1 font-bold text-emerald-500">
        Lass uns gemeinsam unsere schöne Stadt noch l(i)ebenswerter machen.
      </p>
    </div>
    <div class="container mx-auto px-4 pt-16 pb-16 md:pt-20">
      <div class="grid grid-cols-6 gap-8">
        <div v-for="(project, i) in projects" class="col-span-6 lg:col-span-3" :class="{
          'xl:col-span-2': indexToColSpan(i) * 2 == 2,
          'xl:col-span-4': indexToColSpan(i) * 2 == 4,
        }">
          <ProjectCard :title="project.title" :sub-title="project.sub_title" :project-id="project.id"
            :image-id="project.image" :image-size="indexToColSpan(i) * 2 == 2 ? 'small' : 'large'" />
        </div>
      </div>
      <NuxtLink to="/projekte"
        class="text-md font-header mt-12 inline-flex items-center rounded-md bg-green-100 py-1.5 px-4 font-bold transition ease-in-out hover:bg-green-200 focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-opacity-75">
        Alle Projekte
        <svg xmlns="http://www.w3.org/2000/svg" class="ml-1 h-4 w-4" fill="none" viewBox="0 0 24 24"
          stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
        </svg>
      </NuxtLink>
    </div>
    <section class="bg-slate-100 py-24">
      <div class="container mx-auto grid grid-cols-1 gap-8 px-4 lg:grid-cols-2">
        <div>
          <h4 class="text-sm font-semibold uppercase text-gray-600">
            Lebe deine Stadt
          </h4>
          <h1 class="font-header mt-2 text-4xl font-bold">
            Ehrenamtlich, engagiert, miteinander
          </h1>
        </div>
        <div>
          <p>
            Alle sind eingeladen, sich mit Ideen, Zeit und Geld für eine
            <b>positive Entwicklung Potsdams einzubringen</b>. Wir vernetzen
            Gleichgesinnte, versammeln engagierte Menschen, bieten Unterstützung
            als Plattform für Ehrenamt und möchten es den Menschen in Potsdam
            leichter machen, das <b>Gemeinwohl zu stärken</b>,
            Gemeinschaftsgefühl zu erleben, ein
            <b>herzliches Miteinander</b> und eine starke Zukunft für Potsdam zu
            stiften.
          </p>
        </div>
      </div>
    </section>
    <section class="py-24">
      <div class="container mx-auto grid gap-8 px-4 grid-cols-6">
        <div class="col-span-6 lg:col-span-4">
          <h4 class="text-sm font-semibold uppercase text-gray-600">
            Von unserem Blog
          </h4>
          <h1 class="font-header mt-2 text-4xl font-bold">
            Aktuelles & Neuigkeiten
          </h1>
          <p class="mt-4 max-w-2xl">Verfolgen Sie die Entwicklung unserer Projekte, die dank Ihrer großzügigen Beiträge
            und ihrer Unterstützung möglich wurden.</p>
          <NuxtLink to="/stiftung/aktuelles"
            class="text-md font-header mt-12 mb-4 inline-flex items-center rounded-md bg-green-100 py-1.5 px-4 font-bold transition ease-in-out hover:bg-green-200 focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-opacity-75">
            Alle Beiträge
            <svg xmlns="http://www.w3.org/2000/svg" class="ml-1 h-4 w-4" fill="none" viewBox="0 0 24 24"
              stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
            </svg>
          </NuxtLink>
        </div>
        <div v-for="post in posts" class="min-h-max col-span-6 lg:col-span-3 xl:col-span-2">
          <ArticleCard :title="post.title" :date="new Date(post.date)" :post-id="post.id.toString()"
            :image-id="post.image" :project-title="post.project.title" :tags="post.tags" compact
            :link="`/stiftung/aktuelles/${post.id}`" />
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: "default",
});

const { getItems } = useDirectusItems();

const projects = await getItems<any>({
  collection: "projects",
  params: {
    sort: "sort",
    limit: 7,
    fields: ["title", "sub_title", "image", "id"],
  },
});

const posts = await getItems<any>({
  collection: "posts",
  params: {
    fields: [
      "title",
      "date",
      "id",
      "image",
      "tags",
      "project.*.title",
    ],
    limit: 4,
    sort: "-date",
  }
})

const indexToColSpan = useGridSpanLayout();
</script>

// apps/website/pages/index.tsx
import {
  Box,
  Container,
  Flex,
  Grid,
  GridItem,
  Heading,
  Link,
  List,
  ListItem,
  SimpleGrid,
  Text,
  Wrap,
} from "@chakra-ui/layout";
import { Default } from "@components/layouts";
import { ProjectGrid } from "@components/project";
import projects from "@config/projects.json";

const mappedProjects = projects.map((project) => ({
  ...project,
  link: `/projekte/${project.slug}`,
}));

export default function Home() {
  return (
    <>
      <Box w="full" pt="40" pb="10" zIndex="2" bg="white">
        <Container maxW="container.xl">
          <Heading color="secondary" size="4xl" mb="6">
            Brücken bauen,
            <br /> Menschen verbinden
            <Text as="span" color="#38A169" lineHeight="inherit">
              .
            </Text>
          </Heading>
          <Text>
            Wir sind die Potsdamer Bürgerstiftung und fördern als
            Mitmach-Stiftung ehrenamtliches Engagement.
            <br />{" "}
            <Link>
              Lasst uns gemeinsam unsere schöne Stadt noch l(i)ebenswerter
              machen.
            </Link>
          </Text>
        </Container>
      </Box>
      <Box w="full" bg="white" py="4">
        <Container maxW="container.xl">
          <Flex align="center">
            <Wrap
              as={List}
              fontFamily="heading"
              fontWeight="bold"
              align="center"
              spacing="3"
            >
              <ListItem>
                <Text fontWeight="normal">Projekte filtern nach</Text>
              </ListItem>
              <ListItem>
                <Text>-</Text>
              </ListItem>
              <ListItem>
                <Link>Kultur</Link>
              </ListItem>
              <ListItem>
                <Text>/</Text>
              </ListItem>
              <ListItem>
                <Link>Soziales</Link>
              </ListItem>
              <ListItem>
                <Text>/</Text>
              </ListItem>
              <ListItem>
                <Link>Umweltschutz</Link>
              </ListItem>
            </Wrap>
          </Flex>
          <Box pt="8">
            <ProjectGrid projects={mappedProjects} />
          </Box>
        </Container>
      </Box>
      <Box w="full" bg="white" pb="24" pt="24">
        <Container maxW="container.xl">
          <Grid
            columns={2}
            spacing="10"
            templateColumns="repeat(5, 1fr)"
            gap={6}
          >
            <GridItem colSpan={2}>
              <Heading as="h2" size="lg" mb="4" variant="subtitle">
                Unser Motto
              </Heading>
              <Heading as="h2" size="xl" mb="4" maxW="md">
                Ehrenamtlich, engagiert, miteinander
              </Heading>
            </GridItem>
            <GridItem colSpan={3}>
              <Text>
                Alle sind eingeladen, sich mit Ideen, Zeit und Geld für eine{" "}
                <b>positive Entwicklung Potsdams einzubringen</b>. Wir vernetzen
                Gleichgesinnte, versammeln engagierte Menschen, bieten
                Unterstützung als Plattform für Ehrenamt und möchten es den
                Menschen in Potsdam leichter machen, das{" "}
                <b>Gemeinwohl zu stärken</b>, Gemeinschaftsgefühl zu erleben,
                ein herzliches Miteinander und eine starke Zukunft für Potsdam
                zu stiften.
              </Text>
            </GridItem>
          </Grid>
        </Container>
      </Box>
    </>
  );
}

Home.Layout = Default;
