// apps/pbswebsite/components/ArticleCard.tsx
import Link from "next/link";
import Image from "next/image";
import classNames from "classnames";

const ArticleCard: React.FC<{
  title: string;
  date: Date;
  imageId?: string;
  projectTitle?: string;
  author?: string;
  tags?: string[];
  compact?: boolean;
  link?: string;
}> = (props) => {
  const {
    compact = false,
    title,
    date,
    imageId,
    projectTitle,
    author,
    tags,
    link,
  } = props;

  const formattedDate = date.toLocaleDateString("de", {
    year: "numeric",
    day: "numeric",
    month: "long",
  });

  return (
    <Link href={link ?? ""} className="group relative block h-full w-full overflow-hidden rounded-md">
      {imageId && (
        <div
          className={classNames(
            "overflow-hidden",
            compact
              ? "absolute bottom-0 top-0 left-0 right-0"
              : "relative aspect-[5/4]"
          )}
        >
          <Image
            src={imageId}
            height="700"
            width="700"
            quality="40"
            alt=""
            className={classNames(
              "h-full w-full object-cover transition duration-500",
              { "group-hover:scale-110": !compact }
            )}
          />
          <div
            className={classNames(
              "absolute left-0 right-0 bottom-0 transition duration-500",
              compact
                ? "top-0 bg-slate-900 bg-opacity-60"
                : "translate-y-3 bg-gradient-to-t from-slate-900 to-transparent p-6 opacity-0 group-hover:translate-y-0 group-hover:opacity-100"
            )}
          >
            {!compact && (
              <div className="relative flex flex-row items-center font-bold">
                <span className="text-white">Beitrag aufrufen</span>
                <div className="ml-2 h-0.5 w-12 bg-white" />
              </div>
            )}
          </div>
        </div>
      )}
      <div
        className={classNames(
          "relative bg-slate-100 px-6 py-8 transition",
          compact ? "h-full hover:bg-transparent" : "hover:bg-slate-200"
        )}
      >
        <ul className="flex">
          <li className={classNames({ "group-hover:text-white": compact })}>
            {formattedDate}
          </li>
          <li
            className={classNames(
              "text-md text-slate-500 before:px-1.5 before:text-emerald-500 before:content-['•']",
              { "group-hover:text-white": compact }
            )}
          >
            {projectTitle}
          </li>
        </ul>
        <h2
          className={classNames("font-header mt-3 text-3xl font-bold", {
            "group-hover:text-white": compact,
          })}
        >
          {title}
        </h2>
        {tags && (
          <ul className="mt-4 flex flex-wrap gap-2">
            {tags.map((tag, index) => (
              <Link
                href="/aktuelles"
                key={index}
                className={classNames(
                  "rounded-md bg-slate-200 py-1 px-2 text-sm font-medium transition hover:bg-slate-300",
                  {
                    "group-hover:bg-opacity-10 group-hover:text-white": compact,
                  }
                )}
              >
                {tag}
              </Link>
            ))}
          </ul>
        )}
      </div>
    </Link>
  );
};

export default ArticleCard;

// apps/pbswebsite/components/article/ArticleCard.vue
<template>
  <NuxtLink
    :to="`/aktuelles/${postId}`"
    class="group block w-full overflow-hidden rounded-md"
  >
    <div class="relative aspect-[5/4] overflow-hidden" v-if="imageId">
      <DirectusImage
        :asset-id="imageId"
        :width="700"
        :height="700"
        :quality="40"
        class="h-full w-full object-cover transition duration-500 group-hover:scale-110"
      />
      <div
        class="absolute left-0 right-0 bottom-0 translate-y-3 bg-gradient-to-t from-slate-900 to-transparent p-6 opacity-0 transition duration-500 group-hover:translate-y-0 group-hover:opacity-100"
      >
        <div class="relative flex flex-row items-center font-bold">
          <span class="text-white">Beitrag aufrufen</span>
          <div class="ml-2 h-0.5 w-12 bg-white" />
        </div>
      </div>
    </div>
    <div class="bg-slate-100 px-6 py-8">
      <ul class="flex">
        <li class="text-md font-medium text-slate-500">{{ formattedDate }}</li>
        <li
          class="text-md text-slate-500 before:px-1.5 before:text-emerald-500 before:content-['•']"
          v-if="projectTitle"
        >
          {{ projectTitle }}
        </li>
      </ul>
      <h2 class="font-header mt-3 text-3xl font-bold">{{ title }}</h2>
      <ul v-if="tags" class="mt-4 flex flex-wrap gap-2">
        <li v-for="tag in tags">
          <NuxtLink
            to="/aktuelles"
            class="rounded-md bg-slate-200 py-1 px-2 text-sm font-medium transition hover:bg-slate-300"
          >
            {{ tag }}
          </NuxtLink>
        </li>
      </ul>
    </div>
  </NuxtLink>
</template>

<script setup lang="ts">
// Article Card Props
const { date } = defineProps<{
  postId: string;
  title: string;
  date: Date;
  imageId?: string;
  projectTitle?: string;
  author?: string;
  tags?: string[];
}>();

const formattedDate = date.toLocaleDateString("de", {
  year: "numeric",
  day: "numeric",
  month: "long",
});
</script>
