// apps/website/components/project/ProjectCard/ProjectCard.tsx
import { FC, useState, useEffect } from "react";
import {
  Box,
  Heading,
  Stack,
  Text,
  VStack,
  LinkBox,
  LinkOverlay,
  Flex,
} from "@chakra-ui/layout";
import Image from "next/image";
import NextLink from "next/link";
import { motion } from "framer-motion";

export interface ProjectCardProps {
  title: string;
  description: string;
  imageUrl: string;
  link: string;
}

const MotionText = motion(Text);
const MotionBox = motion(Box);
const MotionStack = motion(Stack);

const ProjectCard: FC<ProjectCardProps> = ({
  title,
  description,
  imageUrl,
  link,
}) => {
  const [isHovered, setHovered] = useState(false);

  return (
    <LinkBox
      rounded="lg"
      w="full"
      h="20rem"
      bg="background"
      position="relative"
      overflow="hidden"
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      <MotionBox
        animate={{ scale: isHovered ? 1.1 : 1 }}
        position="relative"
        height="full"
        width="full"
        transition={{ ease: "easeOut", duration: 0.3 }}
      >
        <Image
          src={imageUrl}
          alt="sad"
          layout="fill"
          sizes="1000px"
          objectFit="cover"
          quality="50"
        />
      </MotionBox>
      <Box
        position="absolute"
        top="0"
        right="0"
        left="0"
        bottom="0"
        bgGradient="linear(to-b, transparent, blackAlpha.600 100%)"
        pointerEvents="none"
      />
      <Flex
        position="absolute"
        direction="column"
        justify="flex-end"
        top="0"
        bottom="0"
        right="0"
        left="0"
        padding="8"
      >
        <VStack align="left" spacing="1">
          <Heading size="md" color="white">
            <NextLink href={link} passHref>
              <LinkOverlay>{title}</LinkOverlay>
            </NextLink>
          </Heading>
          <Box position="relative" pointerEvents="none">
            <MotionText
              color="gray.200"
              animate={{ opacity: isHovered ? 0 : 1, y: isHovered ? -20 : 0 }}
              transition={{ ease: "easeOut", duration: 0.35 }}
            >
              {description}
            </MotionText>
            <MotionStack
              position="absolute"
              direction="row"
              align="center"
              animate={{ opacity: isHovered ? 1 : 0, y: isHovered ? 0 : 20 }}
              transition={{ ease: "easeOut", duration: 0.35 }}
              top="0"
            >
              <Text as="span" fontWeight="bold" color="white">
                Projekt anzeigen{" "}
              </Text>
              <Box height="2px" width="50px" bg="white" />
            </MotionStack>
          </Box>
        </VStack>
      </Flex>
    </LinkBox>
  );
};

export default ProjectCard;

// apps/pbswebsite/components/project/card/ProjectCard.vue
<template>
  <NuxtLink
    :to="`/projekte/${projectId}`"
    class="group relative block h-96 w-full cursor-pointer overflow-hidden rounded-lg"
  >
    <img
      :src="`https://cms.potsdamer-buergerstiftung.org/assets/${imageId}?${imageProps}&quality=40`"
      class="h-full w-full object-cover transition duration-500 group-hover:scale-110"
      :alt="`Bild von ${title}`"
    />
    <div
      class="pointer-events-none absolute top-0 bottom-0 left-0 right-0 bg-gradient-to-t from-black via-transparent to-transparent opacity-80"
    />
    <div
      class="flex-column absolute top-0 bottom-0 left-0 right-0 flex items-end p-8"
    >
      <div class="relative w-full">
        <h1 class="font-header text-2xl font-bold text-white">{{ title }}</h1>
        <div class="relative mt-2 w-full overflow-hidden">
          <p
            class="block translate-y-0 text-white opacity-100 transition duration-500 group-hover:-translate-y-3 group-hover:opacity-0"
          >
            {{ subTitle }}
          </p>
          <div
            class="absolute translate-y-0 text-white opacity-0 transition duration-500 group-hover:-translate-y-full group-hover:opacity-100"
          >
            <div class="relative flex flex-row items-center font-bold">
              <span>Projekt anzeigen</span>
              <div class="ml-2 h-0.5 w-12 bg-white" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </NuxtLink>
</template>

<script setup lang="ts">
const { imageSize = "small" } = defineProps<{
  title: string;
  imageId: string;
  subTitle: string;
  projectId: string;
  imageSize?: "small" | "large";
}>();

const imageProps =
  imageSize == "small" ? "width=500&height=500" : "width=1100&height=900";
</script>
