// apps/website/pages/kontakt.tsx
import {
  Box,
  Button,
  Container,
  Divider,
  Grid,
  GridItem,
  Heading,
  Link,
  Text,
  VStack,
} from "@chakra-ui/react";
import { Breadcrumb } from "@components/core";
import PageTitle from "@components/core/PageTitle";
import ComingSoon from "@components/layouts/ComingSoon";

export default function ContactPage() {
  return (
    <>
      <PageTitle
        title="Kontakt"
        contentBottom
        description="Schreib uns, ruf an oder komm vorbei. Wir freuen uns auf dich."
      >
        <Button
          colorScheme="green"
          bg="brand"
          as="a"
          href="mailto:hallo@inselbuehne-potsdam.de"
        >
          Schreib uns eine E-Mail
        </Button>
      </PageTitle>
      <Box as="section" pt="20" bg="white">
        <Breadcrumb items={[{ label: "Kontakt", link: "/kontakt" }]} />
      </Box>
      <Box as="section" bg="white" pt="10" pb="20">
        <Container maxW="container.xl">
          <Grid templateColumns="repeat(5, 1fr)" gap={10}>
            <GridItem colSpan={2}>
              <Heading size="lg" mb="6">
                Telefon &amp; E-Mail
              </Heading>
              <Text fontWeight="bold">0331 23180309</Text>
              <Text fontWeight="bold">hallo@inselbuehne-potsdam.de</Text>
              <Text mt="5">Arbeitszeiten:</Text>
              <Text>Montag - Donnerstag</Text>
              <Text>9 Uhr - 15 Uhr</Text>
            </GridItem>
            <GridItem colSpan={1}>
              <Heading size="lg" mb="6">
                Komm vorbei
              </Heading>
              <Box>
                <Text fontWeight="bold">MAZ-Pyramide</Text>
                <Text>Friedrich-Engels-Straße 24</Text>
                <Text>14473 Potsdam</Text>
              </Box>
              <Box mt="8">
                <Text fontWeight="bold">Inselbühne</Text>
                <Text>Burgstraße 8</Text>
                <Text>14467 Potsdam</Text>
              </Box>
            </GridItem>
            <GridItem colSpan={1}>
              <Heading size="lg" mb="6">
                Social Media
              </Heading>
              <VStack gap={0} align="start">
                <Link color="gray.700" href="https://instagram.com/inselbuehne">Facebook</Link>
                <Link color="gray.700" href="https://instagram.com/inselbuehne">Instagram</Link>
              </VStack>
            </GridItem>
          </Grid>
        </Container>
      </Box>
      <Divider />
    </>
  );
}

ContactPage.Layout = ComingSoon;

// apps/pbswebsite/pages/kontakt.vue
<template>
    <div>
        <PageTitle>
            <template #breadcrumb>
                <PageTitleBreadcrumb :items="[{ text: 'Kontakt', to: '/kontakt' }]" />
            </template>
        </PageTitle>
        <section class="bg-slate-100">
            <div class="container mx-auto grid grid-cols-4 gap-8 px-4 py-20">
                <div>
                    <h1 class="font-header text-3xl font-bold">Unsere Standorte</h1>
                    <p class="mt-3">Komm einfach vorbei</p>
                </div>
                <div>
                    <h2 class="font-header text-xl font-bold">MAZ-Pyramide</h2>
                    <p class="mt-4">Friedrich-Engels-Straße 24</p>
                    <p>14472 Potsdam</p>
                    <p class="mt-1 font-bold">+49 331 23180300</p>
                    <p class="mt-4">Arbeitszeiten: Montag - Freitag</p>
                    <p>9 Uhr - 15 Uhr</p>
                </div>
                <div>
                    <h2 class="font-header text-xl font-bold">Inselbühne</h2>
                    <p class="mt-4">Burgstraße</p>
                    <p>14467 Potsdam</p>
                    <p class="mt-1 font-bold">+49 331 23180309</p>
                    <p class="mt-4">Besuchszeiten: Freitag - Samstag</p>
                    <p>18 Uhr - 20 Uhr</p>
                </div>
            </div>
        </section>
        <section class="bg-slate-100">
            <div class="container mx-auto grid grid-cols-4 gap-8 px-4 py-16">
                <div>
                    <h1 class="font-header text-3xl font-bold">Allgemeine Fragen</h1>
                    <p class="mt-4">
                        Füll' einfach das Formular aus oder <b>sende uns eine E-Mail</b>
                    </p>
                </div>
                <div>
                    <h2 class="font-header text-xl font-bold">MAZ-Pyramide</h2>
                    <p class="mt-4">Friedrich-Engels-Straße 24, 14472 Potsdam</p>
                    <p class="mt-1 font-bold">+49 331 23180300</p>
                    <p class="mt-4">Arbeitszeiten: Montag - Freitag</p>
                    <p>9 Uhr - 15 Uhr</p>
                </div>
                <div>
                    <h2 class="font-header text-xl font-bold">Inselbühne</h2>
                    <p class="mt-4">Burgstraße, 14467 Potsdam</p>
                    <p class="mt-1 font-bold">+49 331 23180309</p>
                    <p class="mt-4">Besuchszeiten: Freitag - Samstag</p>
                    <p>18 Uhr - 20 Uhr</p>
                    <NuxtLink to="https://www.inselbuehne-potsdam.de" class="font-bold"
                        >inselbuehne-potsdam.de
                    </NuxtLink>
                </div>
            </div>
        </section>
    </div>
</template>

<script setup lang="ts">
definePageMeta({
    title: "Kontakt",
});
</script>
